### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by yy2058** [gnina/gnina#114]
### Issue summary
CMake Error at test/CMakeLists.txt:20 (message):
  Pytest package not available: Traceback (most recent call last):

    File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
      mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
    File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
      return _get_module_details(pkg_main_name, error)
    File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
      __import__(pkg_name)
    File "/home/xxx/.local/lib/python3.5/site-packages/pytest/__init__.py", line 3, in <module>
      from . import collect
    File "/home/xxx/.local/lib/python3.5/site-packages/pytest/collect.py", line 8, in <module>
      from _pytest.deprecated import PYTEST_COLLECT_MODULE
    File "/home/xxx/.local/lib/python3.5/site-packages/_pytest/deprecated.py", line 11, in <module>
      from _pytest.warning_types import PytestDeprecationWarning
    File "/home/xxx/.local/lib/python3.5/site-packages/_pytest/warning_types.py", line 7, in <module>
      from _pytest.compat import final
    File "/home/xxx/.local/lib/python3.5/site-packages/_pytest/compat.py", line 57, in <module>
      import importlib_metadata  # noqa: F401
    File "/home/xxx/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 159
      dist: Optional['Distribution'] = None
          ^

  SyntaxError: invalid syntax

### Your system configuration
Operating system:ubuntu16.04
Compiler;cmake 3.19
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:3.5.2

**Comment by dkoes** [comment]
Install pytest (e.g. `pip install pytest`)

**Comment by yy2058** [comment]
> Install pytest (e.g. `pip install pytest`)

I try to install pytest. But Pytest package is still not available

**Comment by dkoes** [comment]
If pytest was available in the environment, you wouldn't be getting this error.  Make sure you have installed pytest for python3.5 or configure your build to use a different python.
