### ISSUE TITLE
error train.py

### ISSUE THREAD

**Issue by sunhwan** [gnina/gnina#46]
### Issue summary

Running `train.py` using `refmodel3.model` produces `Message type "caffe.LayerParameter" has no field named "molgrid_data_param"` error message.

    ~/work/gnina/models/refmodel3$ python ../../scripts/train.py -m refmodel3.model -p ../data/csar/all -d ../data/csar
      0           test ../data/csar/alltest0.types
      0          train ../data/csar/alltrain0.types
      1           test ../data/csar/alltest1.types
      1          train ../data/csar/alltrain1.types
      2           test ../data/csar/alltest2.types
      2          train ../data/csar/alltrain2.types
    Traceback (most recent call last):
      File "../../scripts/train.py", line 848, in <module>
        results = train_and_test_model(args, train_test_files[i], outname, cont)
      File "../../scripts/train.py", line 351, in train_and_test_model
        write_model_file(test_model, template, files['train'], test_file, args.data_root, args.avg_rotations)
      File "../../scripts/train.py", line 71, in write_model_file
        prototxt.Merge(f.read(), netparam)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 536, in Merge
        descriptor_pool=descriptor_pool)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
        return parser.MergeLines(lines, message)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
        self._ParseOrMerge(lines, message)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
        self._MergeField(tokenizer, message)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
        merger(tokenizer, message, field)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
        self._MergeField(tokenizer, sub_message)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
        (message_descriptor.full_name, name))
    google.protobuf.text_format.ParseError: 9:3 : Message type "caffe.LayerParameter" has no field named "molgrid_data_param".

### Steps to reproduce

    .. build gnina ; cmake ; make ; make install
    git clone git@github.com:gnina/models.git
    git clone git@github.com:gnina/scripts.git
    cd models/refmodel3
    python ../../scripts/train.py -m refmodel3.model -p ../data/csar/all -d ../data/csar

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: gcc 5.4
CUDA version (if applicable): 9.0
CUDNN version (if applicable): 7.2.1
BLAS: 3.10.2
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7

**Comment by dkoes** [comment]
My guess is you have vanilla caffe installed and that is what is getting pulled in, not the gnina version.

**Comment by sunhwan** [comment]
Thanks, that was the issue indeed. I did `export PYTHONPATH=/usr/local/python`, which contained gnina version of caffe, and it works now.
